// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanesRecetas.infraestructure.Persistence.DomainModel;

#nullable disable

namespace PlanesRecetas.infraestructure.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20260225161525_Base")]
    partial class Base
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Joseco.Outbox.Contracts.Model.OutboxMessage<Joseco.DDD.Core.Abstractions.DomainEvent>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outboxId");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correlationId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit")
                        .HasColumnName("processed");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("processedOn");

                    b.Property<string>("SpanId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("spanId");

                    b.Property<string>("TraceId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traceId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outboxMessage", "outbox");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Care.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoAlimentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoAlimentoId");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Care.Tiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tiempo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "HalfMorning"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Lunch"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "HalfAfternoon"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Dinner"
                        });
                });

            modelBuilder.Entity("PlanesRecetas.domain.Care.TipoAlimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoAlimento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Verdura"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Fruta"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "FrutoSeco"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "CarneRoja"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "CarneBlanca"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Grano"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Carbohidrato"
                        });
                });

            modelBuilder.Entity("PlanesRecetas.domain.Metrics.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("UnidadMedida", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Gramos",
                            Simbolo = "g"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Kilogramos",
                            Simbolo = "kg"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Mililitro",
                            Simbolo = "Ml"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Litro",
                            Simbolo = "L"
                        });
                });

            modelBuilder.Entity("PlanesRecetas.domain.Persons.Nutricionista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Nutricionista", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Persons.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Plan.Dieta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaConsumo")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PlanAlimentacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanAlimentacionId");

                    b.ToTable("Dieta", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Plan.DietaReceta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 2);

                    b.Property<Guid>("DietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TiempoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DietaId");

                    b.HasIndex("RecetaId");

                    b.HasIndex("TiempoId");

                    b.ToTable("DietaReceta", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Plan.PlanAlimentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuracionDias")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATEDIFF(DAY, [FechaInicio], [FechaFin])", true);

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("DATE");

                    b.Property<Guid>("NutricionistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NutricionistaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("PlanAlimentacion", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Recipe.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Calorias")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CantidadValor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Ingrediente", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Recipe.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instrucciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TiempoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TiempoId");

                    b.ToTable("Receta", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Recipe.RecetaIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CantidadValor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("RecetaId");

                    b.ToTable("RecetaIngrediente", (string)null);
                });

            modelBuilder.Entity("PlanesRecetas.domain.Care.Categoria", b =>
                {
                    b.HasOne("PlanesRecetas.domain.Care.TipoAlimento", "TipoAlimento")
                        .WithMany("Categorias")
                        .HasForeignKey("TipoAlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoAlimento");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Plan.Dieta", b =>
                {
                    b.HasOne("PlanesRecetas.domain.Plan.PlanAlimentacion", "PlanAlimentacion")
                        .WithMany("Dietas")
                        .HasForeignKey("PlanAlimentacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAlimentacion");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Plan.DietaReceta", b =>
                {
                    b.HasOne("PlanesRecetas.domain.Plan.Dieta", "Dieta")
                        .WithMany("DietaRecetas")
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanesRecetas.domain.Recipe.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanesRecetas.domain.Care.Tiempo", "Tiempo")
                        .WithMany()
                        .HasForeignKey("TiempoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");

                    b.Navigation("Receta");

                    b.Navigation("Tiempo");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Plan.PlanAlimentacion", b =>
                {
                    b.HasOne("PlanesRecetas.domain.Persons.Nutricionista", null)
                        .WithMany()
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlanesRecetas.domain.Persons.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlanesRecetas.domain.Recipe.Ingrediente", b =>
                {
                    b.HasOne("PlanesRecetas.domain.Care.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlanesRecetas.domain.Metrics.UnidadMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Recipe.Receta", b =>
                {
                    b.HasOne("PlanesRecetas.domain.Care.Tiempo", "Tiempo")
                        .WithMany()
                        .HasForeignKey("TiempoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tiempo");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Recipe.RecetaIngrediente", b =>
                {
                    b.HasOne("PlanesRecetas.domain.Recipe.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanesRecetas.domain.Recipe.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Care.TipoAlimento", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Plan.Dieta", b =>
                {
                    b.Navigation("DietaRecetas");
                });

            modelBuilder.Entity("PlanesRecetas.domain.Plan.PlanAlimentacion", b =>
                {
                    b.Navigation("Dietas");
                });
#pragma warning restore 612, 618
        }
    }
}
