global:
  scrape_interval: 15s      # raspar cada 15 segundos
  evaluation_interval: 15s

scrape_configs:
  # Métricas de la API .NET
  - job_name: planesrecetas.api
    static_configs:
      - targets: ['planes-api:1700']
    metrics_path: /metrics

  # Métricas del propio Prometheus
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']