services:
  planes-postgres:
    image: postgres:15
    container_name: planes_postgres
    networks:
      - shared-network
    restart: always
    env_file:
      - postgres.env
    ports:
      - '5022:5432'
    volumes:
      - postgres-server-data:/var/lib/postgresql/data
    user: "0" # Running as root to avoid permission issues with mounted volumes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appservice"]
      interval: 5s
      timeout: 5s
      retries: 10

  planes-migrate:
    image: ikaru773/planesrecetaswebapi
    command: ["dotnet", "PlanesRecetas.WebApi.dll", "--migrate"]
    depends_on:
      planes-postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DataBaseSettings__ConnectionString=Host=planes-postgres;Port=5432;Database=appservice;Username=postgres;Password=Password12345;
    networks:
      - shared-network

  planes-api:
    image: ikaru773/planesrecetaswebapi
    container_name: planes_receta_api
    ports:
      - "1700:1700"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - ASPNETCORE_ENVIRONMENT=Development
      - DataBaseSettings__ConnectionString=${DB_CONNECTION_STRING};
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__System=Warning
      - UseSecretManager=false
      - JwtOptions__Lifetime=${JWTOPTIONS_LIFETIME}
      - JwtOptions__SecretKey=${JWTOPTIONS_SECRETKEY}
      - JwtOptions__Audience=${JWTOPTIONS_AUDIENCE}
      - JwtOptions__ValidIssuer=${JWTOPTIONS_VALIDISSUER}
      - JwtOptions__ValidateAudience=${JWTOPTIONS_VALIDATE_AUDIENCE}
      - JwtOptions__ValidateIssuer=${JWTOPTIONS_VALIDATE_ISSUER}
      - JwtOptions__ValidateLifetime=${JWTOPTIONS_VALIDATELIFETIME}
      - RabbitMqSettings__Host=${RABBIT_HOST}
      - RabbitMqSettings__Port=5672
      - RabbitMqSettings__UserName=${RABBIT_USER}
      - RabbitMqSettings__Password=${RABBIT_PASSWORD}
      - RabbitMqSettings__QueueName=plan-created
      - RabbitMqSettings__VirtualHost=/
      - ServiceRegistration__ServiceDiscoveryAddress=http://consul:8500
      - ServiceRegistration__Host=http://api-plan
      - ServiceRegistration__Port=8090
      - ServiceRegistration__ServiceId=catalog
      - Seq__ServerUrl=http://seq:5341
      - JaegerSettings__Host=jaeger
      - JaegerSettings__Port=6831
    networks:
      - shared-network
    depends_on:
      planes-postgres:
        condition: service_healthy

  planes-worker:
    image: ikaru773/plans-worker
    container_name: plans-worker
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - ASPNETCORE_ENVIRONMENT=Development
      - DataBaseSettings__ConnectionString=${DB_CONNECTION_STRING};
      - RabbitMqSettings__Host=${RABBIT_HOST}
      - RabbitMqSettings__Port=5672
      - RabbitMqSettings__UserName=${RABBIT_USER}
      - RabbitMqSettings__Password=${RABBIT_PASSWORD}
      - RabbitMqSettings__QueueName=plan-created
      - RabbitMqSettings__VirtualHost=/
    networks:
      - shared-network
    depends_on:
      planes-postgres:
        condition: service_healthy

  loki:
    image: grafana/loki:3.0.0
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - '3100:3100'
    volumes:
      - ../loki/data:/loki 
      - ../loki/config.yml:/etc/loki/local-config.yaml
    networks:
      - shared-network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: unless-stopped
    user: "0" 
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/config.yml:/etc/prometheus/prometheus.yml
      # Notice we map to /prometheus/data to match where your files actually are
      - prometheus_data:/prometheus/data 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data' # This tells Prometheus to look in /data
      - '--storage.tsdb.retention.time=30d'
    networks:
      - shared-network

  grafana:
    image: grafana/grafana:11.0.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning    
    networks:
      - shared-network  
  jaeger:
    image: jaegertracing/all-in-one:latest   
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
    networks:
      - shared-network  


volumes:
  grafana_data:
  prometheus_data:
  postgres-server-data: # Fixed typo from 'posgrest'
    driver: local

networks:
  shared-network:
    driver: bridge
