services:
  plan-api:
    image: ikaru773/planesrecetaswebapi
    container_name: api_planes_receta
    ports:
      - "8090:8090"
    env_file:
      - ../.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
      # Database Settings (pointing to the sqlserver container)
      - DataBaseSettings__ConnectionString=Server=sqlserver;Database=appservice;User Id=sa;Password=Password12345;TrustServerCertificate=True;
      
      # Serilog
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__System=Warning
      
      # Vault / Secret Manager (Set to true or false as needed)
      - UseSecretManager=false
      
      # JWT Options
      - JwtOptions__Lifetime=30
      - JwtOptions__SecretKey=HL#6j=4;5H{5qZ#M=6J!1[W<YvWdbzEif|M]:ZB<6<{ap^K!@Tg{];OD0E
      - JwtOptions__ValidAudience=storeApp
      - JwtOptions__ValidIssuer=identity
      - JwtOptions__ValidateAudience=true
      - JwtOptions__ValidateIssuer=true
      - JwtOptions__ValidateLifetime=true
      
      # RabbitMQ (pointing to the rabbitmq container)
      - RabbitMqSettings__Host=rabbitmq
      - RabbitMqSettings__Port=5672
      - RabbitMqSettings__UserName=guest
      - RabbitMqSettings__Password=guest
      - RabbitMqSettings__QueueName=plan-created
      - RabbitMqSettings__VirtualHost=/
      
      # Service Registration & Monitoring
      - ServiceRegistration__ServiceDiscoveryAddress=http://consul:8500
      - ServiceRegistration__Host=http://api-plan
      - ServiceRegistration__Port=8090
      - ServiceRegistration__ServiceId=catalog
      - Seq__ServerUrl=http://seq:5341
      - JaegerSettings__Host=jaeger
      - JaegerSettings__Port=6831
    networks:
      - app-network-public  # 
    depends_on:
      - sqlserver
  plan-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: plan_sqlserver
    networks:
      - app-network-public
    restart: always
    env_file:
      - sqlserver.env
      - sapassword.env
    ports:
      - '1433:1433'
    volumes:
      - sql-server-data:/var/opt/mssql/
    user: "0"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password12345", "-Q", "select 1"]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
 sql-server-data:
    driver: local
  # The rest of your volumes were removed as they conflicted with standard SQL Server paths
  # If you need them, they must be defined here with the correct syntax:
  # sqldata:
  # sqllog:
  # sqlbackup:
networks:
  app-network-public:
    driver: bridge 
