# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run:  dotnet restore PlanesRecetas.webapi
    - name: Build
      run: dotnet build PlanesRecetas.webapi --no-restore
    - name: Test
      run: dotnet test PlanesRecetas.testing --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Generate coverage report
      run: >
          dotnet tool run reportgenerator
          -reports:"./coverage/**/coverage.cobertura.xml"
          -targetdir:"./coverage/report"
          -reporttypes:Html
